name: analytics
description: A new Flutter package for collecting and sending analytical information from the app.
version: 1.0.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  deriv_rudderstack:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_rudderstack
      ref: 31236c598da4df62d273de53ea1e0d650ed8b8ca

  firebase_analytics: ^8.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
