name: analytics
description: A new Flutter package for collecting and sending analytical information from the app.
version: 1.0.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: "3.7.8"

dependencies:
  deriv_rudderstack:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_rudderstack
      ref: 9fd9ebcc4126a9239db2773e33d6e1fdc400c39f

  firebase_analytics: ^10.1.6
  firebase_core: ^2.7.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
