name: analytics
description: A new Flutter package for collecting and sending analytical information from the app.
version: 1.0.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  deriv_rudderstack:
    git:
      url: git@github.com:waqas-younas-deriv/flutter-deriv-packages.git
      path: packages/deriv_rudderstack
      ref: 881311660a0178c2e6908ddaad2432c31e03fd34

  firebase_analytics: ^8.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
