name: analytics
description: A new Flutter package for collecting and sending analytical information from the app.
version: 1.0.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  deriv_rudderstack:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_rudderstack
      ref: 62281f9a1f005fcf168e121b579bf3f1a9f4ae5e

  deriv_api_key_provider:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_api_key_provider
      ref: 62281f9a1f005fcf168e121b579bf3f1a9f4ae5e

  firebase_analytics: ^8.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
