name: analytics
description: A new Flutter package for collecting and sending analytical information from the app.
version: 1.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:

  firebase_analytics: ^10.6.2
  firebase_core: ^2.20.0
  rudder_sdk_flutter: ^2.6.0
  datadog_flutter_plugin: ^1.6.2
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.1

flutter:
