name: analytics
description: A new Flutter package for collecting and sending analytical information from the app.
version: 1.0.0
homepage: https://deriv.com/

environment:
  sdk: ">=2.12.0 <3.0.0"

publish_to: "none"

dependencies:
  deriv_rudderstack:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_rudderstack
      ref: dev

  firebase_analytics: ^8.1.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
