name: analytics
description: A new Flutter package for collecting and sending analytical information from the app.
version: 4.4.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.0.0
  firebase_analytics: ^12.0.0
  rudder_sdk_flutter: ^3.2.0
  datadog_flutter_plugin: ^2.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^1.0.4
