// ignore_for_file: public_member_api_docs

import 'package:deriv_theme/src/deriv_colors.dart';
import 'package:deriv_theme/src/dimens.dart';
import 'package:flutter/material.dart';

import 'deriv_text_styles.dart';

/// Holds deriv design system data, based on passed [brightness].
///
/// Through an instance of the [DerivTheme] class, it is possible to
/// access font family, various app colors, and get text style.
class DerivTheme {
  const DerivTheme(this.brightness);

  final Brightness brightness;

  /*
  In case of a theme change, use IDE refactoring technique to rename the values
  So they can be reflected wherever they are used in the app with ease.
  */

  static const DerivColors lightTheme = DerivColors(Brightness.light);
  static const DerivColors darkTheme = DerivColors(Brightness.dark);

  static const double zeroMargin = Dimens.zeroMargin;

  static const double margin01 = Dimens.margin01;

  static const double margin02 = Dimens.margin02;

  static const double margin04 = Dimens.margin04;

  static const double margin06 = Dimens.margin06;

  static const double margin08 = Dimens.margin08;

  static const double margin12 = Dimens.margin12;

  static const double margin16 = Dimens.margin16;

  static const double margin18 = Dimens.margin18;

  static const double margin24 = Dimens.margin24;

  static const double margin32 = Dimens.margin32;

  static const double margin36 = Dimens.margin36;

  static const double margin40 = Dimens.margin40;

  static const double margin44 = Dimens.margin44;

  static const double margin48 = Dimens.margin48;

  static const double margin56 = Dimens.margin56;

  static const double margin64 = Dimens.margin64;

  static const double margin72 = Dimens.margin72;

  static const double margin78 = Dimens.margin78;

  static const double margin84 = Dimens.margin84;

  static const double margin96 = Dimens.margin96;

  static const double margin128 = Dimens.margin128;

  static const double borderRadius04 = Dimens.borderRadius04;

  static const double borderRadius08 = Dimens.borderRadius08;

  static const double borderRadius16 = Dimens.borderRadius16;

  static const double borderRadius100 = Dimens.borderRadius100;

  static const double iconSize8 = Dimens.iconSize8;

  static const double iconSize12 = Dimens.iconSize12;

  static const double iconSize16 = Dimens.iconSize16;

  static const double iconSize24 = Dimens.iconSize24;

  static const double iconSize32 = Dimens.iconSize32;

  static const double iconSize40 = Dimens.iconSize40;

  static const double iconSize48 = Dimens.iconSize48;

  static const double iconSize64 = Dimens.iconSize64;

  static const double iconSize72 = Dimens.iconSize72;

  static const double iconSize96 = Dimens.iconSize96;

  bool get isDarkTheme => brightness == Brightness.dark;

  DerivColors get colors => isDarkTheme ? darkTheme : lightTheme;

  String get fontFamily => DerivTextStyles.appFontFamily;

  /// The style of text is generated by calling this function,
  ///
  /// The `type` argument must not be null, and if null is passed, an
  /// ArgumentError will be thrown
  ///
  /// The 'color` may be null or un-passed, in that case, a default value will
  /// be assigned to it
  TextStyle textStyle({
    required TextStyle textStyle,
    Color? color,
  }) {
    color ??= DerivDarkColors.prominent;

    return textStyle.copyWith(color: color);
  }
}
