name: deriv_theme
description: A flutter package that contains the theme used by deriv products
version: 2.0.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
