name: deriv_api_key_provider
description: deriv api key provider plugin project.
version: 0.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: "3.7.8"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.0.1
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.deriv.deriv_api_key_provider
        pluginClass: DerivApiKeyProviderPlugin
      ios:
        pluginClass: DerivApiKeyProviderPlugin
