name: flutter_deriv_packages
repository: https://github.com/regentmarkets/flutter-deriv-packages

packages:
  - packages/*

command:
  version:
    # Generate commit links in package changelogs.
    linkToCommits: true
    workspaceChangelog: true
    updateGitTagRefs: true

  bootstrap:
    # It seems so that running "pub get" in parallel has some issues (like
    # https://github.com/dart-lang/pub/issues/3404). Disabling this feature
    # makes the CI much more stable.
    runPubGetInParallel: false
