name: deriv_packages_workspace

environment:
  sdk: ">=2.18.0 <4.0.0"

dependency_overrides:
  deriv_http_client:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/deriv_http_client
      ref: deriv_http_client-v2.0.2

  flutter_deriv_api:
    git:
      url: https://github.com/deriv-com/flutter-deriv-api.git
      ref: v1.4.1

  analytics:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/analytics
      ref: analytics-v4.1.1

  deriv_theme:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/deriv_theme
      ref: deriv_theme-v3.0.0

  deriv_ui:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/deriv_ui
      ref: deriv_ui-v0.1.2+2

  deriv_web_view:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/deriv_web_view
      ref: deriv_web_view-v0.2.2+5

  deriv_localizations:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/deriv_localizations
      ref: deriv_localizations-v1.7.2

  deriv_passkeys:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/deriv_passkeys
      ref: deriv_passkeys-v0.0.5+15

  deriv_language_selector:
    git:
      url: https://github.com/deriv-com/flutter-deriv-packages.git
      path: packages/deriv_language_selector
      ref: deriv_language_selector-v0.0.4+2

dev_dependencies:
  melos: 3.2.0
