name: deriv_auth_ui
description: A flutter package for deriv auth UI flows.
version: 0.0.3

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

publish_to: "none"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3

  deriv_auth:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_auth
      ref: deriv_auth-v1.2.2
  deriv_theme:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_theme
      ref: deriv_theme-v2.3.0
  deriv_ui:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_ui
      ref: deriv_ui-v0.0.3
  flutter_svg: ^1.1.6
  smooth_page_indicator: ^1.1.0
  intl_utils: ^2.8.3
  intl: ^0.18.0
  equatable: ^2.0.5
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^0.3.0
  patrol_finders: ^1.0.0
  bloc_test: ^9.1.3

flutter_intl:
  enabled: true
  class_name: DerivAuthUILocalization

flutter:
  assets:
    - assets/icons/
    - assets/images/
