name: deriv_technical_analysis
description: A Dart package for Technical Analysis.
version: 0.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: "3.7.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
