name: deriv_rudderstack
description: A new Flutter plugin to wrap RudderStack SDK.
version: 1.1.0
homepage: https://deriv.com/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.deriv.deriv_rudderstack
        pluginClass: DerivRudderstackPlugin
      ios:
        pluginClass: DerivRudderstackPlugin
