name: deriv_rudderstack
description: A new Flutter plugin to wrap RudderStack SDK.
version: 1.1.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  rudder_sdk_flutter: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0

# flutter:
#   plugin:
#     platforms:
#       android:
#         package: com.deriv.deriv_rudderstack
#         pluginClass: DerivRudderstackPlugin
#       ios:
#         pluginClass: DerivRudderstackPlugin
