name: deriv_localizations
description: This packages contains all localizations for the deriv packages

publish_to: 'none'

version: 1.4.1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter 


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  generate: true
