name: deriv_auth
description: Provides deriv authentication functionalities for dart/flutter apps.
version: 1.0.2
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bloc: ^7.1.0
  collection: ^1.15.0
  crypto: ^3.0.2
  equatable: ^2.0.5
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  lints: ^1.0.1
  mocktail: ^0.2.0
  test: ^1.16.0
