name: deriv_auth
description: Provides deriv authentication functionalities for dart/flutter apps.
version: 2.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

publish_to: "none"

dependencies:
  flutter:
    sdk: flutter

  deriv_theme:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_theme
      ref: deriv_theme-v2.2.0
  deriv_ui:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_ui
      ref: deriv_ui-v0.0.3

  deriv_http_client:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_http_client
      ref: deriv_http_client-v1.0.0

  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  smooth_page_indicator: ^1.1.0
  intl_utils: ^2.8.3
  intl: ^0.18.0
  equatable: ^2.0.5
  package_info_plus: ^4.2.0
  crypto: ^3.0.2
  http: ^0.13.5

dev_dependencies:
  mocktail: ^0.3.0
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  patrol_finders: ^1.0.0

flutter_intl:
  enabled: true
  class_name: DerivAuthLocalization

flutter:
  assets:
    - assets/icons/
    - assets/images/
