name: deriv_auth
description: Provides deriv authentication functionalities for dart/flutter apps.
version: 1.2.1

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  deriv_http_client:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_http_client
      ref: deriv_http_client-v1.0.0

  bloc: ^8.1.1
  crypto: ^3.0.2
  equatable: ^2.0.5
  http: ^0.13.5
  intl: ^0.18.0

dev_dependencies:
  lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.24.1
  bloc_test: ^9.1.3
