name: deriv_auth
description: Provides deriv authentication functionalities for dart/flutter apps.
version: 1.0.2
# homepage: https://www.example.com

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  bloc: ^8.1.1
  crypto: ^3.0.2
  equatable: ^2.0.5
  http: ^0.13.5
  intl: ^0.17.0

dev_dependencies:
  lints: ^2.0.1
  mocktail: ^0.3.0
  test: ^1.24.1
