name: form_builder
description: A simpler and cleaner way to create, validate and submit forms.
homepage: https://github.com/regentmarkets/flutter-deriv-packages
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: "3.7.8"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.24.1
