name: deriv_signup_login
description: A package for handling in app signup and login.
version: 1.1.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
