name: deriv_env
description: A package to load and store environment variables.

version: 0.0.1

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: "3.7.8"

dependencies:
  flutter:
    sdk: flutter

  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - test/.env.test
    - test/.env.empty.test
