name: deriv_web_view
description: Deriv Web View package project.

version: 0.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_deriv_api:
    git:
      url: git@github.com:deriv-com/flutter-deriv-api.git
      ref: dev

  crypto: ^3.0.2
  equatable: ^2.0.3
  flutter_bloc: ^7.0.0
  url_launcher: ^6.1.3
  webview_flutter: ^3.0.4
  flutter_inappwebview: ^5.4.3+7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
