name: deriv_web_view
description: Deriv Web View package project.

version: 0.2.2+5

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.2
  equatable: ^2.0.3
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.1
  flutter_inappwebview: ^6.0.0
  flutter_bloc: ^8.1.2
  deriv_http_client:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_http_client
      ref: deriv_http_client-v2.0.2

dependency_overrides:
  # We've encountered an issue related to package below upon upgrading to flutter 3.22.2 in one of
  # the projects. In order to resolve the issue, we've to update the proguard-rules.pro
  # in the package itself. Due to that, we've created a PR based on the master branch of the package
  # and make use of it as a temporary fix.
  flutter_inappwebview_android:
    git:
      url: git@github.com:weng-deriv/flutter_inappwebview.git
      path: flutter_inappwebview_android
      ref: 9f122f2f549fde62fd0fb911eaab87cc9da85903

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
