name: deriv_web_view
description: Deriv Web View package project.

version: 0.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_deriv_api:
    git:
      url: git@github.com:bassam-deriv/flutter-deriv-api.git
      ref: new-flutter-3.10

  deriv_api_key_provider:
    git:
      url: git@github.com:bassam-deriv/flutter-deriv-packages.git
      path: packages/deriv_api_key_provider
      ref: flutter-3.10

  crypto: ^3.0.2
  equatable: ^2.0.3
  bloc: ^8.1.1
  url_launcher: ^6.1.10
  webview_flutter: ^4.0.0
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
