name: deriv_web_view
description: Deriv Web View package project.

version: 0.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  flutter_deriv_api:
    git:
      url: git@github.com:deriv-com/flutter-deriv-api.git
      ref: flutter-version-3

  crypto: ^3.0.2
  equatable: ^2.0.3
  url_launcher: ^6.1.10
  webview_flutter: ^4.2.1
  flutter_inappwebview: ^5.7.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
