arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: date_range_localizations.dart
output-class: DateRangeLocalizations
output-dir: lib/l10n/generated
synthetic-package: false
nullable-getter: false
