name: deriv_ui
description: A package to put all common deriv flutter widgets and themes.
version: 0.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  build_runner:
  mockito: ^5.0.8
  decimal: ^1.2.0
  intl_utils: ^2.0.0
  webview_flutter: ^2.0.7

  flutter_deriv_api:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-api.git
      ref: dev

  flutter_deriv_bloc_manager:
   git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_bloc_manager
      ref: dev

  deriv_lint:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_lint
      ref: dev

#  deriv_theme:
#    git:
#      url: git@github.com:rajeevqss/flutter-deriv-packages.git
#      path: packages/deriv_theme
#      ref: move-common-ui

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
