name: deriv_ui
description: A package to put all common deriv flutter widgets and themes.
version: 0.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^0.23.0+1
  intl_utils: ^2.0.0
  webview_flutter: ^2.0.7
  decimal: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_deriv_api:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-api.git
      ref: dev


  deriv_lint:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_lint
      ref: dev

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

