name: deriv_language_selector
description: A package to select language for the app. It provides both UI and logic for language selection.
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  deriv_ui:
    git:
      url: git@github.com:regentmarkets/flutter-deriv-packages.git
      path: packages/deriv_ui
      ref: f8bf9eb1ab7e52a18f3139a5f8a459d5569ee85c
  shared_preferences: ^2.2.2
  flutter_bloc: ^8.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/icons/flags/ic_flag_en.png
    - assets/icons/flags/ic_flag_id.png
    - assets/icons/flags/ic_flag_pt.png
    - assets/icons/flags/ic_flag_vi.png
    - assets/icons/flags/ic_flag_zh.png
    - assets/icons/flags/ic_flag_es.png
    - assets/icons/flags/ic_flag_fr.png
    - assets/icons/flags/ic_flag_it.png
    - assets/icons/flags/ic_flag_de.png
    - assets/icons/flags/ic_flag_ru.png
    - assets/icons/flags/ic_flag_th.png
    - assets/icons/flags/ic_flag_pl.png
    - assets/icons/flags/ic_flag_ar.png
    - assets/icons/flags/ic_flag_ko.png
    - assets/icons/flags/ic_flag_sw.png
