name: form_builder_example
description: An example project to demonstrate FormBuilder package.
homepage: https://github.com/regentmarkets/flutter-deriv-packages
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: "3.7.8"

dependencies:
  flutter:
    sdk: flutter
  form_builder:
    path: ../

flutter:
  uses-material-design: true
