name: form_builder_example
description: An example project to demonstrate FormBuilder package.
homepage: https://github.com/regentmarkets/flutter-deriv-packages
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  form_builder:
    path: ../

flutter:
  uses-material-design: true
