name: deriv_app_performance
description: A performance monitoring package for flutter projects
version: 0.2.1

homepage: https://deriv.com/

environment:
  sdk: ">=3.3.3 <4.0.0"
  flutter: ">=3.24.1"

dependencies:
  flutter:
    sdk: flutter

  # Firebase Performance Monitoring
  firebase_performance: ^0.11.0

  # Core dependencies
  equatable: ^2.0.7
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  test: ^1.25.7

flutter:
  # No assets or fonts needed for this package
