name: deriv_rudderstack_example
description: Demonstrates how to use the deriv_rudderstack plugin.

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.10.0"

dependencies:
  deriv_rudderstack:
    path: ../

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
