name: deriv_datadog
description: A wrapper around datadog_flutter_plugin to make it easier to use.

version: 0.0.1

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  datadog_flutter_plugin: ^1.3.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.4.0

flutter:
