name: example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  firebase_core: ^1.7.0
  firebase_database: ^8.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0

  update_checker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
