name: example
description: A new Flutter project.
version: 1.0.0+1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  firebase_core: ^2.4.1
  firebase_database: ^10.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

  update_checker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
