name: example
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase_core: ^1.0.1
  firebase_database: ^6.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0-nullsafety.5
  update_checker:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
