name: flutter_deriv_bloc_manager_example
description: Demonstrates how to use the flutter_deriv_bloc_manager plugin.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: "3.10.2"

dependencies:
  flutter:
    sdk: flutter

  flutter_deriv_bloc_manager:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
