name: deriv_survicate
description: A plugin for run survicate surveys on iOS and Android platforms.
version: 0.0.1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.deriv.deriv_survicate
        pluginClass: DerivSurvicatePlugin
      ios:
        pluginClass: DerivSurvicatePlugin
