name: update_checker
description: Check and retrieve update information from the server for the given package.
version: 3.2.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.7
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  package_info_plus: ^8.3.1
  firebase_database: ^12.0.0
  firebase_remote_config: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.1
  mocktail: ^1.0.4
  test: ^1.25.7
