name: update_checker
description: Check and retrieve update information from the server for the given package.
version: 1.1.0
author: Deriv
homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  equatable: ^2.0.0
  firebase_database: ^7.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  mockito: ^5.0.5
  package_info: ^2.0.0

dev_dependencies:
  bloc_test: any
  flutter_test:
    sdk: flutter
  test: any
