name: update_checker
description: Check and retrieve update information from the server for the given package.
version: 1.1.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  bloc: ^7.2.1
  equatable: ^2.0.3
  firebase_database: ^8.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  mockito: ^5.0.16
  package_info: ^2.0.2

dev_dependencies:
  bloc_test: any
  flutter_test:
    sdk: flutter
  test: any
