name: update_checker
description: Check and retrieve update information from the server for the given package.
version: 1.1.0

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: "3.7.8"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  firebase_database: ^10.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  package_info_plus: ^3.0.3

dev_dependencies:
  bloc_test: ^9.1.1
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  test: ^1.21.4
