name: example
description: A new Flutter project.
version: 1.0.0+1

homepage: https://deriv.com/
publish_to: "none"

environment:
  sdk: ">=2.19.5 <3.0.0"
  flutter: "3.7.8"

dependencies:
  flutter:
    sdk: flutter

  deriv_signup_login:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
