name: Check PR with Title "chore(version)"

on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Check if PR with title chore(version) exists
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT }}
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              per_page: 100
            });

            const existingPR = pullRequests.find(pr => pr.title === 'chore(version): bump version and update changelog');

            if (existingPR) {
              core.setFailed(`A pull request titled 'chore(version)' already exists: #${existingPR.number}`);
            } else {
              console.log("No pull request titled 'chore(version)' found.");
            }

      - name: Fail if PR exists
        if: steps.check-pr.outputs.exists == 'true'
        run: |
          echo "A PR with the title 'chore(version)' already exists. Exiting."
          exit 1
